import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../app/custom-css/scrollbar.css"
import Navbar from "@/components/page-component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="absolute w-full z-50">
        <Navbar />
      </div>
        {children}
      </body>
    </html>
  );
}
